### ISSUE TITLE
TriangularPyramidAndPoint (intersections.h)

### ISSUE THREAD

**Issue by Salamence064** [aggie-coding-club/Zeta-Physics-Engine#101]
### **Recommended Members: 3**
Function signature: `inline bool Zeta::TriangularPyramidAndPoint(TriangularPyramid const &tri, ZMath::Vec3D const &point);`
This should should return 1 if the given point is contained within the given triangular pyramid and 0 otherwise. You should solve this problem by hand first before putting it into code. Be sure to collaborate with your teammates and reference the math techniques in ZetaResources if needed.

**Comment by sai-barath** [comment]
self-assigning to this
