### ISSUE TITLE
removeRigidBodies (physicshandler.h)

### ISSUE THREAD

**Issue by Salamence064** [aggie-coding-club/Zeta-Physics-Engine#98]
### **Recommended Members: 1**
Function Signature: `bool Handler::removeRigidBodies(RigidBody3D** rbs, int size);`
Create an removeRigidBodies function for the Handler class. The function should take in a dynamic array of RigidBody3D*s and the size of that array. It will return 1 if all rigid bodies were found and deleted. Each rigid body should have its memory freed before it is removed from the handler. You should plan this out before writing the code and reference other functions as templates when needed

**Comment by sai-barath** [comment]
assigning myself to this
