### ISSUE TITLE
Create removeStaticBodies (physicshandler.h)

### ISSUE THREAD

**Issue by Salamence064** [aggie-coding-club/Zeta-Physics-Engine#99]
### **Recommended Members: 1**
Function Signature: `bool Handler::removeStaticBodies (StaticBody3D** sbs, int size);`
Create an removeStaticBodies function for the Handler class. The function should take in a dynamic array of StaticBody3D*s and the size of that array. It will return 1 if all static bodies were found and deleted. Each static body should have its memory freed before it is removed from the handler. You should plan this out before writing the code and reference other functions as templates when needed

**Comment by sai-barath** [comment]
assigning myself to this
